### ISSUE TITLE
Error when submitting webform

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-tech-consultancy#129]
@dedenbangkit and @joycarpediem I found this error when testing webforms on UAT1. 

When trying to submit the webform I get a 500. But then at 2nd attempt (I did not leave the browser or do anything, just wait), I could make the submission. See the gif showing it happen twice, with the error logged. 

Let me know if you need more info to be able to resolve this. 

![submitting a webform](https://user-images.githubusercontent.com/12456965/83156324-92048e00-a102-11ea-8599-09cf582bb6f1.gif)

**Comment by dedenbangkit** [comment]
It is because the photo of the file has spaces and our backend trying to retrieve the file without re-regex the filename stored in our backend. We have a different approach recommended by Ivan, by sending the photo directly to S3 without any processing. But we need to wait until some backend feature is fixed.

Reference: https://github.com/akvo/akvo-tech-consultancy/commit/f70065d97e9c2c2c4a2cf8fee47614ef16b32f57

**Comment by janagombitova** [comment]
Tested UAT1 just now and could not reproduce the issue anymore. All resolved
